---
- name: SNMP ro/rw string configuration 
  hosts: tag_cisco 
#  gather_facts: no 
  collections:
  - cisco.ios

  tasks:
    - name: Print out connection variables 
      debug:
        msg:
          - "{{ ansible_connection }}"
          - "{{ ansible_network_os }}"

    - name: IOS - Gather facts
      cisco.ios.ios_facts:
        gather_subset: "all"  #default is !config (all except config)
      when: ansible_network_os|default('') == 'ios'
      register: gathered_ios_facts          

    - name: Ensure the desired SNMP strings are present 
      ios_config:
        commands:
          - snmp-server community ansible-public RO
          - snmp-server community ansible-private RW
